export const countries = {
    KW: "Kuwait",
    KE: "Kenya",
    SD: "Sudan",
    TD: "Chad",
    SL: "Sierra Leone",
    SN: "Senegal",
    NR: "Republic of Nauru",
    SG: "Singapore",
    BA: "Bosnia and Herzegovina",
    BG: "Bulgaria",
    AL: "Albania",
    AE: "United Arab Emirates",
    AT: "Austria",
    BB: "Barbados",
    BT: "Bhutan",
    EC: "Ecuador",
    FJ: "Fiji",
    CR: "Costa Rica",
    BZ: "Belize",
    LI: "Liechtenstein",
    BV: "Bouvet Island",
    PL: "Poland",
    MG: "Madagascar",
    NZ: "New Zealand",
    HM: "Heard Island and McDonald Islands",
    PW: "Palau",
    PY: "Paraguay",
    QA: "Qatar",
    RO: "Romania",
    RU: "Russia",
    RW: "Rwanda",
    VU: "Vanuatu",
    WF: "Wallis and Futuna",
    WS: "Samoa",
    AD: "Andorra",
    IO: "British Indian Ocean Territory",
    AU: "Australia",
    BD: "Bangladesh",
    TH: "Thailand",
    BH: "Bahrain",
    BO: "Bolivia",
    ZA: "Republic of South Africa",
    BQ: "Bonaire, Saint Eustatius, and Saba",
    BR: "Brazil",
    BW: "Botswana",
    CF: "Central African Republic",
    CG: "Republic of the Congo",
    CH: "Switzerland",
    CN: "China",
    CV: "Republic of Cabo Verde",
    FI: "Finland",
    GB: "United Kingdom",
    GD: "Grenada",
    GE: "Georgia",
    GH: "Ghana",
    PG: "Papua New Guinea",
    RS: "Serbia",
    CK: "Cook Islands",
    YE: "Yemen",
    FO: "Faroe Islands",
    SC: "Seychelles",
    GM: "The Gambia",
    GQ: "Equatorial Guinea",
    GT: "Guatemala",
    HR: "Croatia",
    GP: "Guadeloupe",
    MV: "Maldives",
    AF: "Afghanistan",
    SO: "Somalia",
    JO: "Hashemite Kingdom of Jordan",
    HU: "Hungary",
    IQ: "Iraq",
    CY: "Cyprus",
    IS: "Iceland",
    JP: "Japan",
    KG: "Kyrgyzstan",
    KH: "Cambodia",
    HK: "Hong Kong S.A.R",
    ER: "Eritrea",
    KN: "St Kitts and Nevis",
    CS: "Serbia and Montenegro",
    KP: "North Korea",
    CI: "Ivory Coast",
    AN: "Netherlands Antilles",
    EE: "Estonia",
    KZ: "Kazakhstan",
    LA: "Laos",
    HN: "Honduras",
    BJ: "Benin",
    BI: "Burundi",
    LC: "Saint Lucia",
    LB: "Lebanon",
    LK: "Sri Lanka",
    GL: "Greenland",
    LS: "Lesotho",
    LT: "Republic of Lithuania",
    CL: "Chile",
    LV: "Latvia",
    MX: "Mexico",
    LY: "Libya",
    NP: "Nepal",
    CO: "Colombia",
    TO: "Tonga",
    MC: "Monaco",
    AR: "Argentina",
    MT: "Malta",
    MU: "Mauritius",
    FM: "Micronesia",
    ID: "Indonesia",
    UY: "Uruguay",
    IL: "Israel",
    TK: "Tokelau",
    DK: "Denmark",
    DO: "Dominican Republic",
    MD: "Republic of Moldova",
    MH: "Marshall Islands",
    MM: "Myanmar",
    MR: "Mauritania",
    MZ: "Mozambique",
    FR: "France",
    TL: "Timor-Leste",
    IR: "Iran",
    JM: "Jamaica",
    NA: "Namibia",
    GY: "Guyana",
    NE: "Niger",
    XK: "Republic of Kosovo",
    DM: "Dominica",
    KI: "Kiribati",
    GN: "Guinea",
    NG: "Nigeria",
    NI: "Nicaragua",
    NL: "Netherlands",
    NO: "Norway",
    LR: "Liberia",
    OM: "Oman",
    PK: "Pakistan",
    PS: "Palestine",
    PT: "Portugal",
    SA: "Saudi Arabia",
    SE: "Sweden",
    SI: "Slovenia",
    SK: "Slovakia",
    SM: "San Marino",
    ST: "São Tomé and Príncipe",
    MK: "North Macedonia",
    SV: "El Salvador",
    SY: "Syria",
    SZ: "Eswatini",
    TF: "French Southern Territories",
    MW: "Malawi",
    PH: "Philippines",
    TG: "Togo",
    TJ: "Tajikistan",
    TM: "Turkmenistan",
    BL: "Saint Barthélemy",
    UM: "U.S. Minor Outlying Islands",
    TT: "Trinidad and Tobago",
    TW: "Taiwan ROC",
    TZ: "Tanzania",
    UG: "Uganda",
    UZ: "Uzbekistan",
    VC: "St Vincent and Grenadines",
    VE: "Venezuela",
    SS: "Republic of South Sudan",
    VI: "U.S. Virgin Islands",
    HT: "Haiti",
    EG: "Egypt",
    PE: "Peru",
    DJ: "Djibouti",
    US: "United States of America",
    YT: "Mayotte",
    VN: "Vietnam",
    CA: "Canada",
    CD: "DR Congo",
    GR: "Greece",
    AS: "American Samoa",
    PN: "Pitcairn Islands",
    AQ: "Antarctica",
    CW: "Curaçao",
    BF: "Burkina Faso",
    CU: "Cuba",
    GW: "Guinea-Bissau",
    DZ: "Algeria",
    ES: "Spain",
    ET: "Ethiopia",
    NC: "New Caledonia",
    MQ: "Martinique",
    PF: "French Polynesia",
    NF: "Norfolk Island",
    SJ: "Svalbard and Jan Mayen",
    IM: "Isle of Man",
    ML: "Mali",
    MA: "Morocco",
    BE: "Belgium",
    KR: "Republic of Korea",
    MS: "Montserrat",
    SH: "Saint Helena",
    GU: "Guam",
    VG: "British Virgin Islands",
    DE: "Germany",
    LU: "Luxembourg",
    AZ: "Azerbaijan",
    CZ: "Czech Republic",
    AW: "Aruba",
    CX: "Christmas Island",
    FK: "Falkland Islands",
    GI: "Gibraltar",
    MN: "Mongolia",
    PM: "Saint Pierre and Miquelon",
    IE: "Ireland",
    UA: "Ukraine",
    AG: "Antigua and Barbuda",
    CM: "Cameroon",
    ZM: "Zambia",
    TN: "Tunisia",
    AM: "Armenia",
    AX: "Åland Islands",
    BS: "Bahamas",
    AO: "Angola",
    ZW: "Zimbabwe",
    BN: "Brunei",
    GG: "Guernsey",
    TR: "Turkey",
    TV: "Tuvalu",
    MP: "Northern Mariana Islands",
    PR: "Puerto Rico",
    MO: "Macao S.A.R",
    IN: "India",
    SR: "Suriname",
    ME: "Montenegro",
    KM: "Comoros",
    GA: "Gabon",
    GF: "French Guiana",
    RE: "Réunion",
    SB: "Solomon Islands",
    PA: "Panama",
    JE: "Jersey",
    BY: "Belarus",
    CC: "Cocos [Keeling] Islands",
    EH: "Western Sahara",
    KY: "Cayman Islands",
    MY: "Malaysia",
    AI: "Anguilla",
    MF: "Saint Martin",
    NU: "Niue",
    SX: "Sint Maarten",
    BM: "Bermuda",
    GS: "South Georgia and the South Sandwich Islands",
    IT: "Italy",
    VA: "Vatican City",
    TC: "Turks and Caicos Islands"
}